kiplot:
  version: 1

preflight:
  update_xml: true
  ignore_unconnected: true

outputs:
  - name: 'ibom'
    comment: "Interactive Bill of Materials (HTML)"
    type: ibom
    dir: docs/bom
    options:
      dark_mode: false
      hide_pads: true
      show_fabrication: true
      hide_silkscreen: true
      highlight_pin1: true
      no_redraw_on_drag: true
      board_rotation: 0
      checkboxes: 'Sourced,Placed'
      include_tracks: true
      include_nets: true
      sort_order: 'C,R,L,D,U,Y,X,F,SW,A,~,HS,CNN,J,P,NT,MH'
      blacklist: 'DNF*'
      no_blacklist_virtual: true
      blacklist_empty_val: true
      extra_fields: 'EF'
      normalize_field_case: true
      dnp_field: 'DNP'
      name_format: ''
      output: '%f.%x'
